
package net.weweave.tubewarder.test.soap.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SendService", targetNamespace = "http://soap.service.tubewarder.weweave.net/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SendService {


    /**
     * 
     * @param message
     * @return
     *     returns net.weweave.tubewarder.test.soap.client.SendServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "send", targetNamespace = "http://soap.service.tubewarder.weweave.net/", className = "net.weweave.tubewarder.test.soap.client.Send")
    @ResponseWrapper(localName = "sendResponse", targetNamespace = "http://soap.service.tubewarder.weweave.net/", className = "net.weweave.tubewarder.test.soap.client.SendResponse")
    public SendServiceResponse send(
        @WebParam(name = "message", targetNamespace = "")
        SoapSendModel message);

}
