
package net.weweave.tubewarder.test.soap.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ws/send", targetNamespace = "http://soap.service.tubewarder.weweave.net/", wsdlLocation = "http://localhost:8080/ws/send?wsdl")
public class Ws_002fSend
    extends Service
{

    private final static URL WS_002FSEND_WSDL_LOCATION;
    private final static WebServiceException WS_002FSEND_EXCEPTION;
    private final static QName WS_002FSEND_QNAME = new QName("http://soap.service.tubewarder.weweave.net/", "ws/send");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ws/send?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WS_002FSEND_WSDL_LOCATION = url;
        WS_002FSEND_EXCEPTION = e;
    }

    public Ws_002fSend() {
        super(__getWsdlLocation(), WS_002FSEND_QNAME);
    }

    public Ws_002fSend(WebServiceFeature... features) {
        super(__getWsdlLocation(), WS_002FSEND_QNAME, features);
    }

    public Ws_002fSend(URL wsdlLocation) {
        super(wsdlLocation, WS_002FSEND_QNAME);
    }

    public Ws_002fSend(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WS_002FSEND_QNAME, features);
    }

    public Ws_002fSend(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Ws_002fSend(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SendService
     */
    @WebEndpoint(name = "ws/send/port")
    public SendService getWs_002fSend_002fPort() {
        return super.getPort(new QName("http://soap.service.tubewarder.weweave.net/", "ws/send/port"), SendService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SendService
     */
    @WebEndpoint(name = "ws/send/port")
    public SendService getWs_002fSend_002fPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.service.tubewarder.weweave.net/", "ws/send/port"), SendService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WS_002FSEND_EXCEPTION!= null) {
            throw WS_002FSEND_EXCEPTION;
        }
        return WS_002FSEND_WSDL_LOCATION;
    }

}
