export enum ErrorCode {
    OK = 0,
    INVALID_INPUT_PARAMETERS = 1,
    OBJECT_LOOKUP_ERROR = 2,
    PERMISSION_DENIED = 3,
    AUTH_REQUIRED = 4,
    TEMPLATE_CORRUPT = 5,
    MISSING_MODEL_PARAMETER = 6,

    FIELD_REQUIRED = 101,
    FIELD_NAME_ALREADY_EXISTS = 102,
    FIELD_INVALID = 103
}